# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x, 20.x, 22.x]
        arch: [x64]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Node ${{ matrix.node-version }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run codegen
    - run: npm run build
    - run: npm test
